version: "3"
services:
  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./vhost.d:/etc/nginx/vhost.d
      - ./conf.d:/etc/nginx/conf.d
      - ./nginx.tmpl:/app/nginx.tmpl
      - ./html:/usr/share/nginx/html
      - ./config:/etc/nginx/config
      - ./certs:/etc/nginx/certs:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

  nginx-letsencrypt:
    container_name: nginx-letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./nginx.tmpl:/nginx.tmpl
      - ./html:/usr/share/nginx/html
    depends_on:
      - nginx-proxy

networks:
  default:
    external:
      name: nginx-proxy
